### ISSUE TITLE
可以支持检测twitch自动开播?

### ISSUE THREAD

**Issue by gw08brdx7g** [HalfMAI/AutoYtB#4]
可以支持检测twitch自动开播?

**Comment by HalfMAI** [comment]
不好意思，这个不支持twitch的自动开播的。如果需要制作的话可能需要参考
https://discuss.dev.twitch.tv/t/how-to-just-check-if-a-channel-is-live/14701/14
或者使用官方的
https://dev.twitch.tv/docs/api/reference#get-streams

**Comment by gw08brdx7g** [comment]
> 不好意思，这个不支持twitch的自动开播的。如果需要制作的话可能需要参考
> https://discuss.dev.twitch.tv/t/how-to-just-check-if-a-channel-is-live/14701/14
> 或者使用官方的
> https://dev.twitch.tv/docs/api/reference#get-streams

我的意思是可以新增这功能?

**Comment by HalfMAI** [comment]
不好意思，这个项目我已经没有继续维护了，这个功能应该不会考虑添加了。
